language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: IHseb6t1ynFfm3ABAE4157SaKFh1y4Brraj2Dnh786LZ/UiAHGRBICsLdlGaFk0w6ZT+yz3rJpNkHnKLIPwjNYCzSJ2fF2YROotfRgkxYOOA0960NiyStkOVG7QlnZzRtxKV9fWaRPQTvaKsk1pVy4rGug1EzDm8KdvTVkdg1rjJnfwf+jLrdXONtG4GlGT+vHljaWmzCPpfcZ0PcAkqsKMOEP+8cZw+QrFwAXdyd0QmqER6qBvJg64caswQ7V3mqvxlBDkipmD3WKuC6E0woIpj0s5xH+J8n5cMYuUI9fMoKmjyMSxg5yRFEuvHrjFb6YrW23DxetRB9Ck7t/L8HQE57g45FUrGx27audwHuuL//7Hwb6WwJB3Ebo67ejJ4+myZtqc+BKLedf1PpbzP/bIfrKpHLR1E6EmWrwwhxyvXdCBqoliAuqyjdcl2IGj8WvRZIB9xg5udsfG+6mk157eWSxxoKkpyfvsdI66T36HZllwaF+BR/16xLxnHN71NV8uaYdEsLEFPNVwVXh9+DHwakFHMb1/6imWo6oElzM8c1kHTZS+phpZJU8VNK5ju3TOP8u75MBJfQzgi+meemGVMsykaSQ1Tw/Eent8qTV57TahXXnNLRUyGzcxBk4vkVcF48Po5oVAa0tcn9Quu3bAj8/Bd92bYL9BGUZryGoY=
  app: sleepy-beyond-35248
